<?php
$GLOBALS['serv']="localhost";
$GLOBALS['usua']="root";
$GLOBALS['pass']="";
$GLOBALS['bdat']="bdproyecto";
//$GLOBALS['serv']="serv1mysql.mysql.database.azure.com";
//$GLOBALS['usua']="adminmysql@serv1mysql";
//$GLOBALS['pass']="***********";
//$GLOBALS['bdat']="dbclientes";
?>